title: 미정
email: icecoppee@gmail.com
description: "미정입니다..."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icecoppee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: icecoppee

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

  # theme: minima
plugins:
  - jekyll-feed

collections:
  wiki:
    output: true

